- azure-kit-demo/src/main/resources/application.yml
- azure-kit-starter/src/main/java/com/vaadin/azure/starter/AzureKitConfiguration.java
- azure-kit-starter/src/main/java/com/vaadin/azure/starter/SerializationProperties.java
- azure-kit-starter/src/test/java/com/vaadin/azure/starter/SerializationPropertiesTest.java
Properties to restrict transient fields inspection are now prefixed by 'vaadin.serialization.transients'.
So now they are 'vaadin.serialization.transients.include-packages' and 'vaadin.serialization.transients.exclude-packages'.
Fixes #38
- [Z] New and existing tests are passing locally with my change.
> refactor!: renamed transient field filter configuration properties

- azure-kit-starter/src/main/java/com/vaadin/azure/starter/sessiontracker/SessionListener.java
- azure-kit-starter/src/main/java/com/vaadin/azure/starter/sessiontracker/backend/BackendConnector.java
- azure-kit-starter/src/main/java/com/vaadin/azure/starter/sessiontracker/backend/HazelcastConnector.java
- azure-kit-starter/src/main/java/com/vaadin/azure/starter/sessiontracker/backend/RedisConnector.java
- azure-kit-starter/src/main/java/com/vaadin/azure/starter/sessiontracker/push/PushSessionTracker.java
- azure-kit-starter/src/main/java/com/vaadin/azure/starter/sessiontracker/serialization/SerializationDebugRequestHandler.java
- azure-kit-starter/src/test/java/com/vaadin/azure/starter/sessiontracker/SessionListenerTest.java
- azure-kit-starter/src/test/java/com/vaadin/azure/starter/sessiontracker/backend/HazelcastConnectorTest.java
- azure-kit-starter/src/test/java/com/vaadin/azure/starter/sessiontracker/backend/RedisConnectorTest.java
- azure-kit-starter/src/test/java/com/vaadin/azure/starter/sessiontracker/push/PushSessionTrackerTest.java
When the HTTP session expires and gets destroyed
the backend connector is engaged to remove the
replicate session data
Fixes #31
> feat: delete backend data when HTTP session expires

- azure-kit-starter/src/main/java/com/vaadin/azure/starter/sessiontracker/serialization/TransientInjectableObjectOutputStream.java
- azure-kit-starter/src/test/java/com/vaadin/azure/starter/sessiontracker/serialization/SerializationDeserializationTest.java
Inspecting Java platform classes for transient fields is useless. Avoid inspection for them by default, even if a custom filter is provided.
Fixes #39
> fix: avoid transient fields inspection of Java Platform classes

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java
When optimistic serialization fails with NotSerializableException it does not make sense to attemp pessimistic approach, since it will fail with the same error.
Fixes #49
> fix: dont attempt pessimistic on NotSerializableException

- kubernetes-kit-demo/pom.xml
Production profile used flow-maven-plugin instead of vaadin-maven-plugin and for this reason, the final artifact had not the productionMode flag set to true
> fix: use vaadin-maven-plugin in production profile

- kubernetes-kit-demo/deployment/app-v1.yaml
- kubernetes-kit-demo/deployment/app-v2.yaml
- kubernetes-kit-demo/deployment/hazelcast.yaml
- kubernetes-kit-demo/deployment/ingress-v1-add-header.yaml
- kubernetes-kit-demo/deployment/ingress-v1.yaml
- kubernetes-kit-demo/deployment/ingress-v2-use-canary.yaml
- kubernetes-kit-demo/deployment/ingress-v2.yaml
- kubernetes-kit-demo/deployment/redis.yaml
Remove the namespace `canary` from the k8s manifests. If the namespace is not specified the `default` is used.
With this change the to code will be up-to-date with the README and the documentation.
Fixes #57
> fix: Remove namespace canary from the k8s manifests

- LICENSE
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitProperties.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/SerializationProperties.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/CurrentKey.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionListener.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerCookie.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerFilter.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SpringApplicationContext.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/BackendConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/BackendUtil.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/HazelcastConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/RedisConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/SessionInfo.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/NotifyingPushConnection.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/PushSendListener.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/PushSessionTracker.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/SerializationDebugRequestHandler.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/SpringTransientHandler.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientAwareHolder.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientDescriptor.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientHandler.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientInjectableObjectInputStream.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientInjectableObjectOutputStream.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/ui/ClusterSupport.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/ui/SessionDebugNotifier.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/ui/SwitchVersionListener.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/ui/VersionNotifier.java
- pom.xml
This adds the LICENSE file to the repo root, `<license>` tag to the parent POM and license header to all files in `kubernetes-kit-starter`.
> Add license file and headers

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientInjectableObjectInputStream.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientInjectableObjectOutputStream.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/DebugMode.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/DebugTransientHandler.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java
When running debug tool, if multiple optimistic serialization attemps are performed the results are duplicated when printed on server logs. With this change debug tool is reset every time a serialization attempt starts.
> fix: clear debug tool results when serialization starts

- kubernetes-kit-starter/pom.xml
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/LicenseCheckerServiceInitListener.java
- kubernetes-kit-starter/src/main/resources/META-INF/services/com.vaadin.flow.server.VaadinServiceInitListener
- kubernetes-kit-starter/src/main/resources/kubernetes-kit.properties
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/KubernetesKitConfigurationTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/LicenseCheckerServiceInitListenerTest.java
- kubernetes-kit-starter/src/test/resources/kubernetes-kit.properties
- pom.xml
This moves the license check from a static block to a `VaadinServiceInitListener` so that the check can be done once the `VaadinService` instance is available to know if the app is run in development or production mode.
The check is then performed only if running in development mode.
> Use service listener to check the license

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java
In a previous change we replaced `@AutoConfiguration(afterName=...)` with
`@AutoConfigureAfter` annotation, but the latter seems not to activate
the autoconfiguration stuff.
This patch add back the `@AutoConfiguration` annotation, so that kit
configuration are automatically applied at application boot.
> fix: reintroduce Autoconfiguration annotaion

- kubernetes-kit-demo/src/main/resources/application.yml
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/SerializationProperties.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/DebugBackendConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Outcome.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Result.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/SerializationDebugRequestHandler.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/VaadinReplicatedSessionDevModeConfigurationTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/SerializationDebugRequestHandlerTest.java
- Makes serialization timeout configurable to wait for the serialization to be completed (default timeout has been increased to 30s)
- If using SpringBoot then a `timeout` property in `SerializationProperties` is available to set the timeout
- If not using SpringBoot then a `vaadin.serialization.timeout` system property is available to set the timeout
- Updates log messages to make it more clear when a serialization timeout happens and when a serialization job is finished
- Adds check for serialization timeout when updating the result messages in `Job::complete` to avoid `ConcurrentModificationException` because in case of timeout the serialization could still run and updating the messages too
Closes #94 and #97
> Add serialization timeout configurable property

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionListener.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/NotifyingPushConnection.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/PushSendListener.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/PushSessionTracker.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionListenerTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/push/NotifyingPushConnectionTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/push/PushSessionTrackerTest.java
When PUSH transport is websocket, the request associated to atmosphere is a stub implementation that always returns false for 'isRequestedSessionIdValid()' preventing PushSessionTracker to serialize the session.
In addition, accessing the request from a background thread may throw IllegalStateException if the servlet container is recycling request objects (e.g. Tomcat facade). With this change, the session validity is checked against the SessionListener that is already observing session lifecycle events.
Fixes #119
> fix: fix session serialization for PUSH with websocket

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/DebugBackendConnector.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java
If the backed connector fails or hangs during serialization enqueue phase, the UI may freeze or behave incorrectly.
This change makes all backed operations run asynchronously so that the user is not affected by errors caused by the session storage.
Fixes #114
> fix: make backend operation asynchronous

- kubernetes-kit-demo/src/main/java/com/vaadin/kubernetes/demo/generator/DataGenerator.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/DebugBackendConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Outcome.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/SerializationDebugRequestHandler.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/FailingToStringReplacerTest.java
Refactors SerializationDebugRequestHandler and DebugBackendConnector to improve performance.
Using a single SessionSerializer instance prevents creation of multiple (never stopped) executor services, serialization timeouts due to locks of VaadinSession because of concurrent requests, and excessive memory usage to store serialized data in memory for concurrent requests. Requests occurring during a serialization process are now silently ignored, (how it happens in production) since SessionSerializer has its own mechanism to guarantee that all changes are serialized.
Part of #128
Fixes #125
> refactor: debug tool improvements

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/SerializationDebugRequestHandlerTest.java
Based on the JDK version, SerializedLambda.readResolve may differently wrap the cause of error.
This change analyzes the exception to unwrap the root cause of the failure, allowing the debug tool to provide the trace of potential unserializable lambda candidates.
References #135
> fix: unwrap lambda deserialization cause

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerCookie.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerFilter.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerCookieTest.java
Currently clusterKey cookie is set only when an HTTP session exists. In addition to the cookie, the key is also set as a session attribute so that SessionSerializer can fetch it later.
However, if two or more concurrent requests are sent from the client, all of them create a new cookie, but the session attribute gets the value of the first one. This causes the distributed session to be written with a wrong key and when there a server switch the session cannot be restored. This change sets the clusterKey cookie even if there is not yet an HTTP session, so the key is only defined during first request and remains stable with subsequent calls; once the HTTP session is create, the key is stored as an attribute.
Potentially fixes #111
See …
> fix: set clusterKey cookie at first request

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/ui/ClusterSupport.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/ui/ClusterSupportTest.java
VaadinRequest thread local is not available during a VaadinSession.access execution. VaadinRequest is used to access the HTTP session wrapper, that can be obtained through VaadinSession. The most important usage is however getting the update version header, but the lookup can be done outside the access block. This change also removes ClusterSupport registration in CurrentInstance becuase it seems not to be used anywhere and furhtermore the thread local is set only on the thread that calls serviceInit and never cleaned up.
Fixes #148
> fix: prevent usage of VaadinRequest in access

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/DebugBackendConnector.java
In case of serialization failure, the debug backend connector can receive a null SessionInfo object, but the missing null check may interrupt the process preventing the job lock to be released early, causing false timeouts.
> fix: prevent NPE in serialization debug

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientInjectableObjectOutputStream.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/DebugBackendConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/Job.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/SerializationDebugRequestHandler.java
Prevents concurrent request to hijack an ongoing serialization job causing timeouts.
Fixes #147
> fix: improve debug tool performance

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitProperties.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerCookie.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerFilter.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/PushSessionTracker.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerCookieTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerFilterTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/push/PushSessionTrackerTest.java
Allows to set a custom name for the cluster key cookie by setting the `vaadin.kubernetes.cluster-key-cookie-name` property in `application.properties`.
Fixes #145
> feat: allow configuration of custom cluster cookie name

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitProperties.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/HazelcastConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/RedisConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/SessionExpirationPolicy.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/SessionInfo.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/SerializationDebugRequestHandler.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/KubernetesKitConfigurationTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/backend/HazelcastConnectorTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/backend/RedisConnectorTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/backend/SessionInfoTest.java
Allows to define an expiration policy for the backend stored session. By default no expiration is set, but can be expiration can be activated setting the vaadin.kubernetes.backend-session-expiration-tolerance property or by providing a custom SessionExpirationPolicy bean.
Fixes #126
> feat: add configurable backend session expiration policy

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java
Currently, the Spring Security filter chain is executed before SessionTrackerFilter restores the HTTP session, causing Vaadin security checks to fail even if the user information is available in the serialized session. This change fixes the order of the SessionTrackerFilter so that it is always executed before the Spring Security filter chain.
Fixes #170
> fix: ensure SessionTrackerFilter is executed before Spring Security

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/SerializationInputStream.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/SerializationOutputStream.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/SerializationStreamFactory.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientInjectableObjectInputStream.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientInjectableObjectOutputStream.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/TransientInjectableObjectStreamFactory.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/SerializationDebugRequestHandler.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java
This pull request introduces a SerializationStreamFactory bean to provide output and input stream instances, enabling the injection of custom implementations. In our project, we use a custom stream implementation to achieve the following objectives:
- Replace the default transient handling logic with custom logic that, by default, does not serialize any referenced spring beans (even if they're not marked as transient, refer to issue #168 for more details)
- Directly write the serialized output to a zstd compression stream, which in our case compresses down the sessions by a factor of six in a few milliseconds
- Add a micrometer timer that measures the time between creating and closing the stream to monitor serialization runtime
Fixes #168
> Adds pluggable SerializationStreamFactory

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializer.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/BackendConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/HazelcastConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/backend/RedisConnector.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/serialization/debug/DebugBackendConnector.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionSerializerTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/backend/HazelcastConnectorTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/backend/RedisConnectorTest.java
The pending session keys should be removed if there is an error during the serialization. If some error happens during the pending session keys removal (like error while connecting to the backend caches or key deletion error), the TTL for the pending session keys will make sure that those are still removed.
- Marks the serialization failed and deletes/unlocks the pending sessions keys in the Redis/Hazelcast caches when the serialization fails with error before it could be marked as completed
- Adds TTL for the pending session keys when the serialization is marked as started in Redis and Hazelcast connectors. The TTL duration for the pending session keys is set to be the same as for the final session keys
- `RedisConnection` has some deprecated methods (`set()`, `del()`, etc.), those are …
> fix: add ttl for peding session key

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/LicenseCheckerServiceInitListener.java
> refactor: use BaseLicenseCheckerServiceInitListener as super class to LicenseCheckerServiceInitListener

- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/KubernetesKitConfiguration.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionListener.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerFilter.java
- kubernetes-kit-starter/src/main/java/com/vaadin/kubernetes/starter/sessiontracker/push/NotifyingPushConnection.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionListenerTest.java
- kubernetes-kit-starter/src/test/java/com/vaadin/kubernetes/starter/sessiontracker/SessionTrackerFilterTest.java
- Added a destroy callback, that is run when the session tracker filter is destroyed, that stops the session listener and prevents processing any further events
- Added exception handling when PushSendListener instances are not available during the application shutdown
> cp: Stop session listener when session tracker filter is destroyed (#208)
